[tool.ruff]
target-version = "py310"
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "W", "N", "ANN", "B"]
ignore = ["ANN101", "ANN102"]

[tool.mypy]
python_version = "3.10"
strict = true
explicit_package_bases = true
namespace_packages = true
mypy_path = "."
ignore_missing_imports = true
disallow_untyped_defs = true